services:

  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: luabank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  luabank:
    build: .

    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      CHAVE_PRIVADA: ${CHAVE_PRIVADA}

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
