spring.application.name=luabank 
server.port=8080

spring.datasource.url=jdbc:postgresql://postgres:5432/luabank
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


