spring.application.name=luabank 
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/luabank
spring.datasource.username=postgres
spring.datasource.password=Yuri@0713


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
